# Generated by Django 5.2.6 on 2025-10-03 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True)),
                ('rfid', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sr', models.BooleanField(default=False)),
                ('dob', models.DateField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, max_length=80, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=120, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Retired', 'Retired'), ('Resigned', 'Resigned')], default='Active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'faculty',
                'indexes': [models.Index(fields=['department'], name='faculty_departm_62c77d_idx'), models.Index(fields=['status'], name='faculty_status_0846d2_idx'), models.Index(fields=['rfid'], name='faculty_rfid_a921fa_idx'), models.Index(fields=['name'], name='faculty_name_292e2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('level', models.CharField(choices=[('Pre-school', 'Pre-school'), ('Elementary', 'Elementary'), ('High School', 'High School'), ('Senior High School', 'Senior High School'), ('College', 'College')], max_length=20)),
                ('course', models.CharField(blank=True, max_length=120, null=True)),
                ('block', models.CharField(blank=True, max_length=10, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('strand', models.CharField(blank=True, max_length=50, null=True)),
                ('year_grade', models.CharField(blank=True, max_length=40, null=True)),
                ('rfid', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, max_length=80, null=True)),
                ('guardian', models.CharField(blank=True, max_length=120, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('contacts', models.JSONField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=120, null=True)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Graduated', 'Graduated'), ('Transferred', 'Transferred')], default='Active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students',
                'indexes': [models.Index(fields=['level'], name='students_level_bd9385_idx'), models.Index(fields=['status'], name='students_status_3ac771_idx'), models.Index(fields=['rfid'], name='students_rfid_534c19_idx'), models.Index(fields=['name'], name='students_name_ead02e_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_type', models.CharField(choices=[('initial', 'initial'), ('re_enrollment', 're_enrollment'), ('transfer', 'transfer')], max_length=20)),
                ('previous_level', models.CharField(blank=True, max_length=20, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=12, null=True)),
                ('previous_year_grade', models.CharField(blank=True, max_length=40, null=True)),
                ('previous_section', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_strand', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_course', models.CharField(blank=True, max_length=120, null=True)),
                ('previous_block', models.CharField(blank=True, max_length=10, null=True)),
                ('new_level', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=12, null=True)),
                ('new_year_grade', models.CharField(blank=True, max_length=40, null=True)),
                ('new_section', models.CharField(blank=True, max_length=50, null=True)),
                ('new_strand', models.CharField(blank=True, max_length=50, null=True)),
                ('new_course', models.CharField(blank=True, max_length=120, null=True)),
                ('new_block', models.CharField(blank=True, max_length=10, null=True)),
                ('enrollment_year', models.CharField(max_length=4)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.student')),
            ],
            options={
                'db_table': 'enrollment_history',
            },
        ),
    ]
