# Generated by Django 5.2.6 on 2025-10-03 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('success', models.BooleanField(default=True)),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rfid_logs',
                'indexes': [models.Index(fields=['rfid'], name='rfid_logs_rfid_d2ed6d_idx'), models.Index(fields=['timestamp'], name='rfid_logs_timesta_37c373_idx'), models.Index(fields=['success'], name='rfid_logs_success_3e606b_idx')],
            },
        ),
    ]
