# Generated by Django 5.2.6 on 2025-10-03 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.PositiveIntegerField()),
                ('patient_type', models.CharField(choices=[('student', 'student'), ('faculty', 'faculty')], max_length=7)),
                ('form_type', models.CharField(max_length=100)),
                ('form_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medical_records',
                'indexes': [models.Index(fields=['patient_id', 'patient_type'], name='medical_rec_patient_23135e_idx'), models.Index(fields=['form_type'], name='medical_rec_form_ty_2e21c8_idx'), models.Index(fields=['created_at'], name='medical_rec_created_d796b8_idx')],
            },
        ),
    ]
